services:
  db:
    image: postgres:latest
    container_name: todolist-db
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./src/config/database:/docker-entrypoint-initdb.d